src/Entity/Dossier.php
<?php

namespace App\Entity;

use App\Repository\DossierRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=DossierRepository::class)
 */
class Dossier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\ManyToOne(targetEntity=Dossier::class, inversedBy="dossiers")
     */
    private $id_dossier;

    /**
     * @ORM\OneToMany(targetEntity=Dossier::class, mappedBy="id_dossier")
     */
    private $dossiers;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="dossiers")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Fichier::class, mappedBy="dossier")
     */
    private $fichiers;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;




    public function __construct()
    {
        $this->date = new DateTime('now');
        $this->dossiers = new ArrayCollection();
        $this->fichiers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getIdDossier(): ?self
    {
        return $this->id_dossier;
    }

    public function setIdDossier(?self $id_dossier): self
    {
        $this->id_dossier = $id_dossier;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getDossiers(): Collection
    {
        return $this->dossiers;
    }

    public function addDossier(self $dossier): self
    {
        if (!$this->dossiers->contains($dossier)) {
            $this->dossiers[] = $dossier;
            $dossier->setIdDossier($this);
        }

        return $this;
    }

    public function removeDossier(self $dossier): self
    {
        if ($this->dossiers->removeElement($dossier)) {
            // set the owning side to null (unless already changed)
            if ($dossier->getIdDossier() === $this) {
                $dossier->setIdDossier(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }

    /**
     * @return Collection|Fichier[]
     */
    public function getFichiers(): Collection
    {
        return $this->fichiers;
    }

    public function addFichier(Fichier $fichier): self
    {
        if (!$this->fichiers->contains($fichier)) {
            $this->fichiers[] = $fichier;
            $fichier->setDossier($this);
        }

        return $this;
    }

    public function removeFichier(Fichier $fichier): self
    {
        if ($this->fichiers->removeElement($fichier)) {
            // set the owning side to null (unless already changed)
            if ($fichier->getDossier() === $this) {
                $fichier->setDossier(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

}

src/Form/DossierType.php
<?php

namespace App\Form;

use App\Entity\Dossier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DossierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Dossier::class,
        ]);
    }
}

src/Controller/DossierController.php
<?php

namespace App\Controller;

use App\Entity\Dossier;
use App\Entity\Fichier;
use App\Form\DossierType;
use App\Form\FichierType;
use App\Repository\DossierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dossier")
 */
class DossierController extends AbstractController
{
    /**
     * @Route("/", name="dossier_index", methods={"GET","POST"})
     */
    public function index(DossierRepository $dossierRepository): Response
    {
        return $this->render('dossier/index.html.twig', [
            'dossiers' => $dossierRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/", name="dossier_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $error="";
        $user=$this->getUser();
        $dossier = new Dossier();
        $form = $this->createForm(DossierType::class, $dossier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dossier->setUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($dossier);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('dossier/new.html.twig', [
            'dossier' => $dossier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dossier_show", methods={"GET","POST"})
     * @param Request $request
     * @param Dossier $dossier
     * @return Response
     */
    public function show(Request $request,Dossier $dossier): Response
    {
        $erreur="";
        $user=$this->getUser();
        $newdossier = new Dossier();
        $fichiers= $dossier->getFichiers();
        $choixformule= $user->getChoixformules()[0];
        $fichier = new Fichier();

        //formulaire des dossiers
        $form1 = $this->createForm(DossierType::class, $newdossier);
        $form1->handleRequest($request);
        //formulaire des fichiers
        $form2 = $this->createForm(FichierType::class, $fichier);
        $form2->handleRequest($request);

        if ($form1->isSubmitted() && $form1->isValid()) {
            $newdossier->setUser($user);
            $newdossier->setIdDossier($dossier);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($newdossier);
            $entityManager->flush();
            return $this->redirectToRoute('dossier_show',['id'=>$dossier->getId()]);


        }

        if ($form2->isSubmitted() && $form2->isValid()) {
            /** @var UploadedFile $document */
            $document = $form2['libelle']->getData();

            if ($document)
            {
                //on récupère la taille du fichier et on la convertie en Mo
                $filetaille=$fichier->convertisseur(filesize($document));
                //On récupère la taille de disponible dans notre memoire
                $taille_disponible= $choixformule->getTailleDisponible();
                $nouvelle_taille_disponible =  $taille_disponible - $filetaille ;
                //si la memoire disponible est inférieur à zéro
                if ($nouvelle_taille_disponible<=0)
                {
                    $this->addFlash('error_memory', 'Votre mémoire est insuffiante');
                    return $this->redirectToRoute('dossier_show',[
                        'id'=>$dossier->getId(),
                    ]);

                }
                //on récupere le nom du document uploader
                $originalFilename = pathinfo($document->getClientOriginalName(), PATHINFO_FILENAME);
                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename.'.'.$document->guessExtension();

                try
                {
                    //on stock le document dans le repertoire approprié
                    $document->move($this->getParameter('document_directory'),$newFilename );
                }
                catch (FileException $e)
                {

                }
                //si la memoire disponible est inférieur à zéro
                if ($nouvelle_taille_disponible<=0)
                {
                    $this->addFlash('erreur', 'Votre mémoire est insuffiante');
                    return $this->redirectToRoute('dossier_show',[
                        'id'=>$dossier->getId(),
                    ]);

                }

                $fichier->setLibelle($newFilename);
                $fichier->setTaille($filetaille);
                $fichier->setDossier($dossier);
                $choixformule->setTailleDisponible($nouvelle_taille_disponible);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($fichier,$choixformule);
                $entityManager->flush();

                return $this->redirectToRoute('dossier_show',['id'=>$dossier->getId()]);
            }

        }

        return $this->render('dossier/show.html.twig', [
            'dossier' => $dossier,
            'fichiers'=>$fichiers,
            'dossiers'=>$dossier->getDossiers(),
            'form1' => $form1->createView(),
            'form2' => $form2->createView(),

        ]);
    }

    /**
     * @Route("/{id}/edit", name="dossier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Dossier $dossier): Response
    {
        $form = $this->createForm(DossierType::class, $dossier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dossier_index');
        }

        return $this->render('dossier/edit.html.twig', [
            'dossier' => $dossier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dossier_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Dossier $dossier)
    {
        //on récupère l'utilisateur connecté
        $user= $this->getUser();
        //on récupère la formule de l'utilisateur
        $choixformule= $user->getChoixformules()[0];
        //on récupère l'id du repertoire parent
        $dossier_parent= $dossier->getIdDossier()->getId();
        //on supprime tout les fichiers dans le dossier
        //on parcourt tous nos fichiers
        if ($dossier->getFichiers()[0]!=null)
        {
            for ($i=0;$i<= count($dossier->getFichiers());$i++)
            {

                $choixformule->setTailleDisponible($dossier->getFichiers()[$i]->getTaille()+ $choixformule->getTailleDisponible());
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($choixformule);
                $entityManager->remove($dossier->getFichiers()[$i]);
                $entityManager->flush();
            }
        }

        if ($this->isCsrfTokenValid('delete'.$dossier->getId(), $request->request->get('_token')))
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($dossier);
            $entityManager->flush();
        }
        return $this->redirectToRoute('dossier_show',['id'=>$dossier_parent]);

    }


}

templates/dossier/_delete_form.html.twig
<form method="post" action="{{ path('dossier_delete', {'id': dossier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dossier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/dossier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<div class="modal-footer">
    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
    <button class="btn btn-primary">Enregistrer</button>
</div>
{{ form_end(form) }}

templates/dossier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Dossier{% endblock %}

{% block body %}
    <h1>Edit Dossier</h1>

    {{ include('dossier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('dossier_index') }}">back to list</a>

    {{ include('dossier/_delete_form.html.twig') }}
{% endblock %}

templates/dossier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossier index{% endblock %}

{% block body %}
    <h1>Dossier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Libelle</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dossier in dossiers %}
            <tr>
                <td>{{ dossier.id }}</td>
                <td>{{ dossier.libelle }}</td>
                <td>
                    <a href="{{ path('dossier_show', {'id': dossier.id}) }}">show</a>
                    <a href="{{ path('dossier_edit', {'id': dossier.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('dossier_new') }}">Create new</a>
{% endblock %}

templates/dossier/new.html.twig
{% block body %}

    {{ include('dossier/_form.html.twig') }}

{% endblock %}

templates/dossier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ dossier }}{% endblock %}

{% block body %}
  <div class="container">
        <div class="dropdown show row">
            {%  if dossier.idDossier != null %}
            <a class="nav-link" href="{{ path('dossier_show',{'id': dossier.idDossier.id}) }}">
                <span class="fas fa-fw fa-folder-open" style="font-size:40px;color:#f4b619;"></span>
                {{ dossier.idDossier }}({{ dossier.idDossier.fichiers|length }})
            </a><span class="h1" style="margin-top: 5px"><strong>\</strong></span>
            {% endif %}
            <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
                <span class="fas fa-fw fa-folder-open" style="font-size:40px;color:#f4b619;"></span>
                {{ dossier }}({{ dossier.fichiers|length }})
            </a>
            <div class="dropdown-menu show">
                <a class="dropdown-item-text" href="#" data-toggle="modal" data-target="#dossierModal" style="color:#f4b619;">
                    <i class="fa fa-folder-plus" style="font-size:30px;"> </i>
                    nouveau dossier
                </a>
                <a class="dropdown-item-text" href="#" data-toggle="modal" data-target="#fichierModal" style="color: navajowhite">
                    <i class="fa fa-file-import" style="font-size:30px;"> </i>
                    nouveau fichier
                </a>
            </div>

        </div>

        <table class="table">
            <thead>
            <tr>
            <tr>
                <th>Libelle</th>
                <th>Date</th>
                <th>Taille</th>
                <th>actions</th>
            </tr>
            </tr>
            </thead>
            <tbody>
            {% for dossier in dossiers %}
                <tr>
                    <td>
                        <a href="{{ path('dossier_show', {'id': dossier.id}) }}">

                            <span class="fas fa-fw fa-folder" style="font-size:40px;color:#f4b619;"></span>
                            {{ dossier }}({{ dossier.fichiers|length }})
                        </a>
                    </td>
                    <td>{{ dossier.date ? dossier.date|date('d/m/y à h:i:s') : '' }}</td>
                    <td></td>
                    <td align="left">
                        <form  method="post" action="{{ path('dossier_delete', {'id': dossier.id}) }}" onsubmit="return confirm('Suppression du dossier?');">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dossier.id) }}">
                            <button class="btn" style="font-size:20px;color:red;margin-top:-3.8px;margin-left: 40px">
                                <span class="fas fa-fw fa-trash-alt"></span>
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            {% for fichier in fichiers %}
                <tr>
                    <td>
                        <a href="{{ path('fichier_show', {'id': fichier.id}) }}">
                            <span class="fas fa-fw fa-file" style="font-size:40px;color:wheat;"></span>
                            {{ fichier.libelle }}
                        </a>
                    </td>
                    <td>{{ fichier.date ? fichier.date|date('d/m/y à h:i:s') : '' }}</td>
                    <td>{{ fichier.taille}}Mo</td>
                    <td class="row">
                        <a  href="{{ path('fichier_show', {'id': fichier.id}) }}">
                            <button class="btn">
                                <span class="fas fa-fw fa-download" style="font-size:20px;color:cadetblue;"></span>
                            </button>
                        </a>
                        <form  method="post" action="{{ path('fichier_delete', {'id': fichier.id}) }}" onsubmit="return confirm('suppression du fichier?');">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fichier.id) }}">
                            <button class="btn" style="font-size:20px;color:red;margin-top:-4px">
                                <span class="fas fa-fw fa-trash-alt"></span>
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {#    les modales #}
    <!-- Ajout dossier-->
    <div class="modal fade" id="dossierModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ajouter un dossier</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(form1) }}
                    {{ form_widget(form1) }}
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                        <button class="btn btn-primary">Enregistrer</button>
                    </div>
                    {{ form_end(form1) }}

                </div>
            </div>
        </div>
    </div>
    <!-- ajout fichier-->
    <div class="modal fade" id="fichierModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ajouter un fichier</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(form2) }}
                    {{ form_widget(form2) }}
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                        <button class="btn btn-primary">Enregistrer</button>
                    </div>
                    {{ form_end(form2) }}

                </div>

            </div>
        </div>
    </div>
    {#    Fin des modales #}


{% endblock %}